BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RecordTypes' AND COLUMN_NAME = 'Code')
    BEGIN
        ALTER TABLE RecordTypes
        ADD Code NVARCHAR(150) NULL;
    END
END