# UAT ENVIRONMENT PUBLIC API pipeline variables

variables: 

  # Configurations from AppSettings
  SqlServerName: 'sql-ngobia-dpwh-prd'
  IdpSqlServerName: 'sql-ngobia-dpwh-prd'
  SqlServerFullyQualifiedDomainName: '$(SqlServerName).database.windows.net'
  SqlDatabaseName: 'sqldb-edms-dpwh-uat'
  IdPSqlDatabaseName: 'sqldb-ngobia-dpwh-idp-uat'
  SqlServerAdministratorLogin: 'sqladmin'
  DefaultConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  IdentityConnectionString: 'Server=$(IdpSqlServerName).database.windows.net;Initial Catalog=$(IdPSqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  StorageAccountConnectionString: '$(StorageAccountConnectionStringUat)'
  EnableSwaggerUI: 'true'
  Environment: 'UAT'
  CorsUrls: 'https://dpwh-edms-trn.movementsoft.com'
  IdentityServerUrl: 'https://dpwh-ngobia-idp-trn.movementsoft.com'

  KeyVaultName: 'kv-ngobia-dpwh-prd'

  # Azure Resource Group Name and ASE details
  ResourceGroupName: 'rg-ngobia-dpwh-prd'
  HostAppServicePlanName: 'asp-ngobia-dpwh-prd'
  HostAppServiceResourceGroupName: 'rg-ngobia-dpwh-prd'

  DpwhIntegrationBaseApiUrl: 'https://apps.dpwh.gov.ph/pis_api_training/webservice.asmx'