# Global Public API pipeline variables

# The environment parameter is passed through from the calling api-pipeline yaml file.
parameters:
- name: environment
  type: string
  default: 'dev'

variables:

  # This is the Azure Service Connection which is used to deploy the ARM template(s).
  # You will need to have one created specific to your project and the DEV environment.
  AzureSubscription: 'SC-NGOBIA'

  # This is the AAD object ID of the Azure Service Connection (NGOBIA DevOps) which is used to deploy the ARM template(s).
  # You will need to have one created specific to your project and the DEV environment.
  AzureDevOpsServiceConnectionObjectId: 'db09627f-10b3-4ddf-ae99-f2cacec14737'

  # This is our Azure Development subscription ID. MovementSoft Subscription
  AzureSubscriptionId: 'c98075bb-7436-4c42-b5aa-f0513533bda4'

  # Directory (dev) ID when viewing in Azure Portal (use the main Tenant - movementsoft)
  AzureTenantId: 'c98075bb-7436-4c42-b5aa-f0513533bda4'

  # Azure location details
  LocationFull: 'Australia East'
  LocationShort: 'australiaeast'
  LocationCode: 'aue'

  ProjectName: 'edms'
  WebAppName: 'app-api-$(ProjectName)-dpwh-${{ parameters.environment }}'
  ApplicationInsightsName: 'app-api-$(ProjectName)-dpwh-${{ parameters.environment }}'

  # Azure KeyVault
  #KeyVaultName: 'kv-edms-shared'
  KeyVaultSkuFamily: 'A'
  KeyVaultSkuName: 'Standard'

  # These ftp variables are will be set in a release task and used to deploy the app service via SFTP.
  ftpserver: ''
  ftpusername: ''
  ftppassword: ''

  DpwhIntegrationApiUserName: '$(DpwhApiUserName)'
  DpwhIntegrationApiPassword: '$(DpwhApiPassword)'
  ArcgisIntegrationUserName: '$(ArcgisIntegrationUserName)'
  ArcgisIntegrationPassword: '$(ArcgisIntegrationPassword)'
  ArcgisIntegrationOrgId: '$(ArcgisIntegrationOrgId)'
# The end!