# PRODUCTION ENVIRONMENT PUBLIC API pipeline variables

variables:

  # Configurations from AppSettings
  SqlServerName: 'sql-ngobia-dpwh-prd'
  IdpSqlDatabaseName: 'sqldb-ngobia-dpwh-idp-prd'
  SqlDatabaseName: 'sqldb-edms-dpwh-prd'
  SqlServerFullyQualifiedDomainName: '$(SqlServerName).database.windows.net'  
  SqlServerAdministratorLogin: 'sqladmin'
  DefaultConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  IdentityConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(IdPSqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  StorageAccountConnectionString: '$(StorageAccountConnectionString)'
  EnableSwaggerUI: 'true'
  Environment: 'Production'
  CorsUrls: 'https://dpwh-edms.movementsoft.com'
  IdentityServerUrl: 'https://dpwh-ngobia-idp.movementsoft.com'

  KeyVaultName: 'kv-ngobia-dpwh-prd'

  # Azure Resource Group Name and ASE details
  ResourceGroupName: 'rg-ngobia-dpwh-prd'
  HostAppServicePlanName: 'asp-ngobia-dpwh-prd'
  HostAppServiceResourceGroupName: 'rg-ngobia-dpwh-prd'

  DpwhIntegrationBaseApiUrl: 'https://apps.dpwh.gov.ph/pis_api/webservice.asmx'