# DEVELOPMENT ENVIRONMENT PUBLIC API pipeline variables

variables:

  # This is the Azure Service Connection which is used to deploy the ARM template(s).
  # You will need to have one created specific to your project and the DEV environment.
  AzureSubscription: 'SC-NGOBIA'

  # This is the AAD object ID of the Azure Service Connection (NGOBIA DevOps) which is used to deploy the ARM template(s).
  # You will need to have one created specific to your project and the DEV environment.
  AzureDevOpsServiceConnectionObjectId: 'db09627f-10b3-4ddf-ae99-f2cacec14737'

  # This is our Azure Development subscription ID. MovementSoft Subscription
  AzureSubscriptionId: 'c98075bb-7436-4c42-b5aa-f0513533bda4'

  # Configurations from AppSettings
  SqlServerName: 'sql-edms-dpwh-dev'
  SqlServerFullyQualifiedDomainName: '$(SqlServerName).database.windows.net'
  SqlDatabaseName: 'sqldb-edms-dpwh-dev'
  IdPSqlDatabaseName: 'sqldb-ngobia-dpwh-idp-dev'
  SqlServerAdministratorLogin: 'sqladmin'
  DefaultConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300;Command Timeout=300'
  IdentityConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(IdPSqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  StorageAccountConnectionString: '$(StorageAccountConnectionString)'  
  EnableSwaggerUI: 'true'
  Environment: 'Development'
  CorsUrls: 'https://localhost:7081,https://localhost:7281,https://dpwh-edms-dev.movementsoft.com'
  IdentityServerUrl: 'https://app-idp-ngobia-dpwh-dev.azurewebsites.net'

  KeyVaultName: 'kv-edms-dpwh-dev'

  # Azure Resource Group Name and ASE details
  ResourceGroupName: 'rg-edms-dpwh-dev'
  HostAppServicePlanName: 'asp-edms-dpwh-dev'
  HostAppServiceResourceGroupName: 'rg-edms-dpwh-dev'

  DpwhIntegrationBaseApiUrl: 'https://apps.dpwh.gov.ph/pis_api_training/webservice.asmx'