# DEVELOPMENT ENVIRONMENT PUBLIC API pipeline variables

variables:  

  # Configurations from AppSettings
  SqlServerName: 'sql-edms-dpwh-dev'
  IdpSqlServerName: 'sql-ngobia-dpwh-dev'
  SqlServerFullyQualifiedDomainName: '$(SqlServerName).database.windows.net'
  SqlDatabaseName: 'sqldb-edms-dpwh-dev'
  IdPSqlDatabaseName: 'sqldb-ngobia-dpwh-idp-dev'
  SqlServerAdministratorLogin: 'sqladmin'
  DefaultConnectionString: 'Server=$(SqlServerName).database.windows.net;Initial Catalog=$(SqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(SqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  IdentityConnectionString: 'Server=$(IdpSqlServerName).database.windows.net;Initial Catalog=$(IdPSqlDatabaseName);Persist Security Info=False;User ID=$(SqlServerAdministratorLogin);Password=$(IdpSqlServerAdministratorPassword);MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300'
  StorageAccountConnectionString: '$(StorageAccountConnectionString)'  
  EnableSwaggerUI: 'true'
  Environment: 'Development'
  CorsUrls: 'https://localhost:7082,https://localhost:7281,https://dpwh-edms-dev.movementsoft.com'
  IdentityServerUrl: 'https://app-idp-ngobia-dpwh-dev.azurewebsites.net'

  KeyVaultName: 'kv-edms-dpwh-dev'

  # Azure Resource Group Name and ASE details
  ResourceGroupName: 'rg-edms-dpwh-dev'
  HostAppServicePlanName: 'asp-edms-dpwh-dev'
  HostAppServiceResourceGroupName: 'rg-edms-dpwh-dev'

  DpwhIntegrationBaseApiUrl: 'https://apps.dpwh.gov.ph/pis_api_training/webservice.asmx'