# Web build and release pipeline

pool:
  #name: Default
  name: Azure Pipelines
  vmImage: 'windows-latest'

# Don't run this pipeline against a commit, only web client.
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src/DPWH.EDMS.Web/*
    - src/DPWH.EDMS.Components/*
    - src/DPWH.EMDS.Shared/*
    exclude:
    - src/*

# Don't run this pipeline against a PR
pr: none

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
  # Build the project
  - stage: Build
    jobs:
      - template: 'jobs/web/web-build-job.yml'

  # Release to DEV
  - stage: DevRelease
    displayName: Release to DEV
    dependsOn: Build
    condition: succeeded('Build')
    jobs:
      - template: 'jobs/web/web-deploy-job.yml'
        parameters:
          environment: dev

  # Release to UAT
  - stage: UatRelease
    displayName: Release to UAT
    dependsOn: DevRelease
    condition: succeeded('DevRelease')
    jobs:
      - template: 'jobs/web/web-deploy-job.yml'
        parameters:
          environment: uat

  # Release to PROD
  - stage: ProdRelease
    displayName: Release to PROD
    dependsOn: UatRelease
    condition: succeeded('UatRelease')
    jobs:
      - template: 'jobs/web/web-deploy-job.yml'
        parameters:
          environment: prd
  
  #The end!