# DEVELOPMENT ENVIRONMENT Client pipeline variables

variables:

  # This is the Azure Service Connection which is used to deploy the ARM template(s). 
  # You will need to have one created specific to your project and the DEV environment.
  AzureSubscription: 'SC-NGOBIA'

  # This is the AAD object ID of the Azure Service Connection (NGOBIA DevOps) which is used to deploy the ARM template(s). 
  # You will need to have one created specific to your project and the DEV environment.
  AzureDevOpsServiceConnectionObjectId: 'db09627f-10b3-4ddf-ae99-f2cacec14737'

  # This is our Azure Development subscription ID. Azure subscription 1
  AzureSubscriptionId: 'c98075bb-7436-4c42-b5aa-f0513533bda4'  
  
  BaseApiUrl: 'https://dpwhedmsapi-dev.movementsoft.com'
  PublicPortalUrl: 'https://app-publicweb-ngobia-dpwh-dev.azurewebsites.net'

  # Configure OpenIdc
  oidc.Authority: 'https://app-idp-ngobia-dpwh-dev.azurewebsites.net'
  oidc.PostLogoutRedirectUri: 'https://dpwh-edms-dev.movementsoft.com'
  oidc.RedirectUri: 'https://dpwh-edms-dev.movementsoft.com/authentication/login-callback'
  
  # Azure Resource Group Name and ASE details
  ResourceGroupName: 'rg-edms-dpwh-dev'
  HostAppServicePlanName: 'asp-edms-dpwh-dev'
  HostAppServiceResourceGroupName: 'rg-edms-dpwh-dev'